services:
  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=${VITE_API_URL}
    volumes:
      - vue_dist:/app/dist-volume

  backend:
    build:
      context: ./backend
    environment:
      - WEBAUTHN_RPID=${WEBAUTHN_RPID}
      - WEBAUTHN_RP_ORIGIN=${WEBAUTHN_RP_ORIGIN}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - PYTHON_OCR_URL=http://ocr:8081/ocr
    volumes:
      - /var/run/postgresql:/var/run/postgresql
    depends_on:
      - frontend
      - redis
      - ocr
      - cloudflared
    restart: unless-stopped


  caddy:
    image: caddy:2-alpine
    ports:
      - "3500:3500"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - vue_dist:/srv/www
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run filelogix
    volumes:
      - /home/owenrhoekstra/.cloudflared:/etc/cloudflared
    restart: unless-stopped

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:6380:6379"

  ocr:
    build: ./ocr
    ports:
      - "127.0.0.1:8081:8081"
    restart: unless-stopped

volumes:
  vue_dist:
